
'beersLawLab.sim.showHomeScreenProperty.changed'
'beersLawLab.sim.screenIndexProperty.changed' 
'beersLawLab.beersLawScreen.model.detector.probe.locationProperty.changed'
'beersLawLab.beersLawScreen.model.detector.valueProperty.changed'
'beersLawLab.beersLawScreen.model.detector.modeProperty.changed'
'beersLawLab.beersLawScreen.model.cuvette.widthProperty.changed'
'beersLawLab.beersLawScreen.model.light.onProperty.changed' 
'beersLawLab.beersLawScreen.model.light.wavelengthProperty.changed'
'beersLawLab.beersLawScreen.model.solutionProperty.changed' 
'beersLawLab.beersLawScreen.model.ruler.locationProperty.changed'
'beersLawLab.beersLawScreen.view.detectorNode.bodyNode.valueNode.changed'
'beersLawLab.beersLawScreen.view.detectorNode.bodyNode.valueNode.textChanged'
'beersLawLab.beersLawScreen.view.wavelengthControls.variableWavelengthProperty.changed' 
'beersLawLab.beersLawScreen.view.wavelengthControls.valueDisplay.textChanged' 
'beersLawLab.beersLawScreen.solutions.drinkMix.concentrationProperty.changed'
'beersLawLab.beersLawScreen.solutions.copperSulfate.concentrationProperty.changed'
'beersLawLab.beersLawScreen.solutions.cobaltIINitrate.concentrationProperty.changed'
'beersLawLab.beersLawScreen.solutions.cobaltChloride.concentrationProperty.changed'
'beersLawLab.beersLawScreen.solutions.potassiumDichromate.concentrationProperty.changed'
'beersLawLab.beersLawScreen.solutions.potassiumChromate.concentrationProperty.changed'
'beersLawLab.beersLawScreen.solutions.nickelIIChloride.concentrationProperty.changed'
'beersLawLab.beersLawScreen.solutions.potassiumPermanganate.concentrationProperty.changed'






'beersLawLab.sim' 
'beersLawLab.homeScreen.view.beersLawScreenLargeButton' 
'beersLawLab.beersLawScreen.view.detectorNode.probeNode.movableDragHandler.dragStarted' 
'beersLawLab.beersLawScreen.view.detectorNode.probeNode.movableDragHandler.dragEnded' 
'beersLawLab.beersLawScreen.view.detectorNode.probeNode.movableDragHandler.dragged' 
'beersLawLab.beersLawScreen.view.cuvetteNode.cuvetteDragHandler.dragStarted' 
'beersLawLab.beersLawScreen.view.cuvetteNode.cuvetteDragHandler.dragEnded' 
'beersLawLab.beersLawScreen.view.cuvetteNode.cuvetteDragHandler.dragged' 
'beersLawLab.beersLawScreen.view.lightNode.button.toggled' 
'beersLawLab.wrapper.showPDF' 
'beersLawLab.wrapper.hidePDF' 
'beersLawLab.beersLawScreen.view.wavelengthControls.variableWavelengthRadioButton.fired' 
'beersLawLab.beersLawScreen.view.wavelengthControls.presetWavelengthRadioButton'.fired 
'beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.thumbInputListener.dragStarted' 
'beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.thumbInputListener.dragEnded' 
'beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.thumbInputListener.dragged' 
'beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.trackInputListener.dragStarted' 
'beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.trackInputListener.dragEnded' 
'beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.trackInputListener.dragged' 
'beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.minusButton.fired' 
'beersLawLab.beersLawScreen.view.wavelengthControls.wavelengthSlider.plusButton.fired' 
'beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.thumb.dragHandler.dragStarted' 
'beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.thumb.dragHandler.dragEnded'
'beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.thumb.dragHandler.dragged'
'beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.track.inputListener.dragStarted' 
'beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.track.inputListener.dragEnded'
'beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.track.inputListener.dragged'
'beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.minusButton.fired' 
'beersLawLab.beersLawScreen.view.solutionControls.concentrationControl.slider.plusButton.fired' 
'beersLawLab.beersLawScreen.view.solutionControls.comboBox.popupShpown' 
'beersLawLab.beersLawScreen.view.solutionControls.comboBox.popupHidden'
'beersLawLab.beersLawScreen.view.solutionControls.comboBox.fired'
'beersLawLab.beersLawScreen.view.rulerNode.movableDragHandler.dragStarted'
'beersLawLab.beersLawScreen.view.rulerNode.movableDragHandler.dragEnded'
'beersLawLab.beersLawScreen.view.rulerNode.movableDragHandler.dragged'



'capacitorLabBasics.capacitanceScreen.model.circuit.currentAmplitudeProperty'

