---
paths:
  parsed_simulations: '../data/parsed simulations/'
  sequenced_simulations: '../data/sequenced simulations/'
experiment:
  class_name: skipgram
  root_name: pw training
  random_seed: 42
  n_folds: 10
...