---
paths:
  parsed_simulations: '../data/parsed simulations/'
  sequenced_simulations: '../data/sequenced_simulations/'
experiment:
  class_name: blank
  root_name: blank
  random_seed: 42
  n_folds: 10
data:
  pipeline:
    sequencer: 17s
    event_filter: nofilt
    break_filter: cumul60br
    adjuster: tscrp
    encoders_aggregators_pairs:
      1:
        - actionspan
        - noagg
      2:
        - 1hot
        - aveagg
      3:
        - 1hot
        - cumulaveagg
      4:
        - actionspan
        - normagg
      # 5:
      #   - sgenc
      #   - aveagg
      # 6:
      #   - sgenc
      #   - cumulaveagg
      # 7:
      #   - sgenc
      #   - flatagg
    encoder: blank
    aggregator: blank
  adjuster:
    limit: blank
    limits: 
      - 10
      - 20
      - 30
      - 40
      - 50
      - 60
      - 70
      - 80
      - 90
      - 100
      - 150
      - 200
      - 250
      - 300
ML:
  pipeline:
    splitter: stratkf
    sampler: nosplr
    task: classification
    model: blank
    scorer: blank
    gridsearch: supgs
    xvalidator: nested_xval
  models:
    classifiers:
      rf:
        dummy_parameters:
          - blank
      1nn:
        dummy_parameters:
          - blank
  splitters:
    stratkf:
      n_folds: 10
      shuffle: True
      stratifier_col: y
  xvalidators:
    nested_xval:
      inner_n_folds: 10
      optim_scoring: roc
  scorers:
    scoring_metrics:
      - accuracy
      - balanced_accuracy
      - precision
      - recall
      - roc
      - balanced_auc
      - overall_auc
...