---
paths:
  parsed_simulations: '../data/parsed simulations/'
  sequenced_simulations: '../data/sequenced simulations/'
experiment:
  class_name: blank
  root_name: blank
  random_seed: 42
  n_folds: 10
data:
  pipeline:
    sequencer: 17s
    event_filter: nofilt
    break_filter: cumul60br
    adjuster: full
    encoders_aggregators_pairs:
      1:
        - 
        - 
      2:
        - 
        - 
    encoder: blank
    aggregator: blank
  adjuster:
    limit: -1
  encoding:
    skipgrams: 'path'
ML:
  pipeline:
    splitter: stratkf
    sampler: nosplr
    task: classification
    models: 
      - rf
      - nn
    model: blank
    scorer: blank
    gridsearch: supgs
    xvalidator: nested_xval
  splitters:
    stratkf:
      n_folds: 10
      shuffle: True
      stratifier_col: y
  xvalidators:
    nested_xval:
      inner_n_folds: 10
      optim_scoring: roc
      param_grid:
        rf:
          n_estimators:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 12
            - 15
            - 20
            - 25
            - 30
          criterion: 
            - gini
            - entropy
          max_depth: 
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
          min_samples_split: 
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
          max_leaf_nodes: 
            - 2
            - 4
            - 8
            - 16
            - 20
            - 24
            - 36
          max_features: 
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 15
            - 20
        nn:
          dense_units:
            - 8
            - 16
            - 32
            - 64
          dropout:
            - 0
            - 0.2
            - 0.4
            - 0.5
          batch_size:
            - 8
            - 16
            - 32
            - 64
          shuffle:
            - True
          epochs:
            - 5
            - 50
            - 100
            - 200
          early_stopping:
            - False
            - True
          verbose:
            - 0
  scorers:
    scoring_metrics:
      - accuracy
      - balanced_accuracy
      - precision
      - recall
      - roc
...