param_grid:
  dense_units:
    - 8
    - 16
    - 32
    - 64
  dropout:
    - 0
    - 0.2
    - 0.4
    - 0.5
  batch_size:
    - 8
    - 16
    - 32
    - 64
  shuffle:
    - True
  epochs:
    - 5
    - 50
    - 100
    - 200
  early_stopping:
    - False
    - True
  verbose:
    - 0
    