      param_grid:
        n_states:
          - 17
        embeddings:
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 25
          - 30
        window_size:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
        optimiser:
          - adam
        early_stopping:
          - True
          - False
        batch_size:
          - 1
          - 8
          - 16
          - 32
        shuffle:
          - True
        epochs:
          - 5
          - 20
          - 50
          - 100
          - 150
          - 200
