      param_grid:
        n_estimators:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 12
          - 15
          - 20
          - 25
          - 30
        criterion: 
          - gini
          - entropy
        max_depth: 
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
        min_samples_split: 
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
        max_leaf_nodes: 
          - 2
          - 4
          - 8
          - 16
          - 20
          - 24
          - 36
        max_features: 
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 15
          - 20