---
paths:
  newsim_parsed: '../data/parsed simulations/beerslaw-lab/sim2/'
  sequenced_simulations: '../data/sequenced_simulations/'
experiment:
  class_name: blank
  root_name: simname
data:
  pipeline:
    sequencer: davidresin
...