---
paths:
  sequenced_simulations: '../data/sequenced simulations/'
experiment:
  class_name: ''
  root_name: monday
  random_seed: 42
  n_folds: 10
  n_classes: -1
data:
  min_length: 10
  pipeline:
    sequencer: ''
    concatenator:
      type: chemconcat
      tasks: 
        - '1'
        - '2'
    event_filter: nofilt
    break_filter: ''
    adjuster: full
    encoder: ''
    skipgram_weights: ''
    skipgram_map: ''
    aggregator: ''
    encoders_aggregators_pairs:
      0: dummy
    encoders:
      - 1hot
      - sgenc
      - actionspan
  adjuster:
    limit: 9320
    limits: 
      - 10
      - 20
      - 30
      - 40
      - 50
      - 60
      - 70
      - 80
      - 90
      - 100
      - 150
      - 200
      - 250
      - 300
ML:
  pipeline:
    splitter: stratkf
    sampler: nosplr
    task: classification
    model: ''
    scorer: 2clfscorer
    gridsearch: supgs
    test_pad: False
    val_pad: False
    train_pad: True
    models:
      - lstm
      # - adaboost
  models:
    classifiers:
      rf:
        dummy_parameters:
          - blank
      1nn:
        dummy_parameters:
          - blank
      sknn:
        dummy_parameters:
          - blank
      svc:
        dummy_parameters:
          - blank
      sgd:
        dummy_parameters:
          - blank
      knn:
        dummy_parameters:
          blank
      adaboost:
        dummy_parameters:
          blank
      lstm:
        dummy_parameters:
          blank
  splitters:
    n_folds: 10
    stratkf:
      shuffle: True
      stratifier_col: y
  xvalidators:
    nested_xval:
      inner_n_folds: 10
      outer_n_folds: 10
      optim_scoring: roc
  scorers:
    scoring_metrics:
      - accuracy
      - balanced_accuracy
      - precision
      - recall
      - roc
      - balanced_auc
      - overall_auc
    carry_on: True
...