---
paths:
  sequenced_simulations: '../data/sequenced_simulations/'
experiment:
  class_name: binconcepts
  root_name: chemlab--seed-
  name: blank
  old_root_name: blank
  random_seed: 129
  n_folds: blank
  n_classes: 2
data:
  min_length: 0
  pipeline:
    sequencer: blank
    sequencer_interval: 5
    sequencer_dragasclick: True
    concatenator:
      type: chemconcat
      tasks: 
        - '2'
    demographic_filter: chemlab
    event_filter: nofilt
    break_filter: blank
    break_threshold: 0.6
    adjuster: tscrp
    encoder: blank
    skipgram_weights: ''
    skipgram_map: ''
    aggregator: blank
    encoders_aggregators_pairs:
      1:
        - actionspan
        - normagg
      2:
        - 1hot
        - aveagg
  adjuster:
    limit: 30
    limits: 
      - 30
      - 40
      - 50
      - 60
  filters:
    interactionlimit: 10
ML:
  pipeline:
    outerfold_index: -10
    gs_splitter: stratkf
    inner_splitter: stratkf
    outer_splitter: stratkf
    sampler: nosplr
    task: classification
    model: rnn_attention
    xvalidator: nonnested
    scorer: 2clfscorer
    gridsearch: nogs
    test_pad: False
    val_pad: False
    train_pad: True
    models:
      - rf
      # - 1nn
      # - adaboost
  permutation:
    label_map: vector_labels
  models:
    classifiers:
      lstm:
        seed: 1
        batch_size: 16
        cell_type: GRU
        dropout: 0.02
        early_stopping: False
        epochs: 30
        loss: auc
        n_cells: 
          - 32
        n_layers: 1
        optimiser: adam
        padding_value: -1
        shuffle: True
        verbose: 1
        save_best_model: False
        flatten: average
      ssan:
        save_best_model: False
        batch_size: 16
        dropout: 0.02
        early_stopping: false
        epochs: 30
        key_cells: 8
        value_cells: 8
        query_cells: 8
        loss: auc
        optimiser: adam
        padding: valid
        padding_value: -1
        pool_size: 64
        seed: 1
        shuffle: true
        stride: 64
        gru_cells: 16
        verbose: 1
  splitters:
    n_folds: 2
    stratkf:
      shuffle: True
      stratifier_col: y
    flatstrat:
      test_path: '../data/experiment_keys/flatstrat_testusernames.pkl'
      train_path: '../data/experiment_keys/flatstrat_trainusernames.pkl'
  xvalidators:
    nested_xval:
      inner_n_folds: 10
      outer_n_folds: 10
      optim_scoring: roc
  scorers:
    scoring_metrics:
      - accuracy
      - balanced_accuracy
      - precision
      - recall
      - roc
      - balanced_auc
      - overall_auc
    carry_on: True
...