path:
  sequenced_simulations: '../data/sequenced_simulations/'
experiment:
  name: incremental
  algorithm: lstm
  features: seconds
  sequencer: stateaction_secondslstm_12
  classname: binary
concatenation:
  report_folder: EDM2022
  concatenator: nconcepts # or nconcepts
scorer:
  type: multi
  scores:
    - balanced_accuracy
    - balanced_auc
    - overall_auc
    - roc
  stratifiers:
    - 'none'
    - gender
    - year
    - field
  n_classes: 
    nconcepts: 4
    vector_labels: 8
    bin: 2
    tri: 3
plotter:
  stratifiers:
    - gender
    - year
    - field
    - no_strat
new_predictions: ''
concatenator: ''