paths:
  parsed_simulations: '../data/parsed simulations/'
  sequenced_simulations: '../data/sequenced_simulations/'
  crawl_path: '../data/temp/'
sequencing:
  sequencer : stateaction_encodedlstm
  length_limit: 10
  interval: 2
  break_threshold: 0.6
  dragasclick: True


