paths:
  parsed_simulations: '../data/parsed simulations/'
  sequenced_simulations: '../data/sequenced_simulations/'
  crawl_path: '../data/temp/'
sequencing:
  sequencer : base_lstmencoded
  length_limit: 10
