paths:
  parsed_simulations: '../data/parsed simulations/'
  sequenced_simulations: '../data/sequenced simulations/'
  crawl_path: '../data/temp/'
sequencing:
  sequencer : lstmencoding
  length_limit: 10
