paths:
  parsed_simulations: '../data/beerslaw/parsed simulations/'
  sequenced_simulations: '../data/beerslaw/sequenced_simulations/'
  crawl_path: '../data/beerslaw/temp/'
sequencing:
  sequencer : simplemorestate_secondsflat
  length_limit: 0
  interval: 5
  break_threshold: 0.6
  dragasclick: True