experiment:
  name: non nested capacitor/lstm
  keyword: xval # common trait within all nested cross val files
  reproduction_path : '../data/reproduction/'
plot_style:
  title: Full Predictions For Chemlab Lab (SSANLSTM for action-state features)
  measure: roc
  carry_on: True
  sizing_mode: stretch_both
  colour_map: cm_algo_feature
  label_map: lm_algo_feature
  style: algo_features
  type: errorplot #errorplot # change in early pred -> lineplot
  boxplot_spacing: 0.4
  radius: 0.005
  bar_length: 0.05
  ncols: 4
  ystyle:
    label: roc
    range:
      - 0.5
      - 1
  xstyle:
    label: classes
    type: groups # change in earlypred
    groups:
      - 2classes
      # - colourbreak
      # - colournobreak
      # - simplestate
      # - simplemorestates
      # - stateaction
      # - secondslstm
      # - binconcepts
      # - field
      # - language
      # - year
      # - yl_
      # - ylf
      # - extended
      # - colourbreak_flat
      # - colournobreak_flat
      # - simplestate
      # - simplemorestates
      # - stateaction
      # - binconcepts
      # - conbin
      # - widbin
      # - coltri
      # - contri
      # - widtri
train_validation:
  metrics:
    - categorical_crossentropy
    - auc
model_checkpoint:
  train_ids: ../data/experiment_keys/flatstrat_trainusernames.pkl
  test_ids: ../data/experiment_keys/flatstrat_testusernames.pkl
  label_map: vector_labels