experiment:
  name: baselines/classes/colbin/RF
  keyword: xval # common trait within all nested cross val files
  # reproduction_path : '../data/reproduction/'
plot_style:
  title: Results for the Binary classifiers (Random Forest baseline, colour binary)
  measure: roc
  carry_on: True
  sizing_mode: stretch_both
  colour_map: cm_algo_feature
  label_map: lm_algo_feature
  style: algo_features
  type: errorplot # change in early pred -> lineplot
  boxplot_spacing: 0.4
  radius: 0.1
  bar_length: 0.9
  ncols: 4
  ystyle:
    label: roc
    range:
      - 0
      - 1.2
  xstyle:
    label: classes
    type: groups # change in earlypred
    groups:
      - extended
      - colourbreak_flat
      - colournobreak_flat
      # - simplestate
      # - simplemorestates
      # - stateaction
      # - binconcepts
      # - conbin
      # - widbin
      # - coltri
      # - contri
      # - widtri
train_validation:
  metrics:
    - categorical_crossentropy
    - auc
model_checkpoint:
  train_ids: ../data/experiment_keys/flatstrat_trainusernames.pkl
  test_ids: ../data/experiment_keys/flatstrat_testusernames.pkl
  label_map: vector_labels