---
paths:
  sequenced_simulations: '../data/sequenced_simulations/'
experiment:
  class_name: 2classes
  root_name: edm_repro
  name: 'edmrepro_actioncount'
  random_seed: 42
  n_folds: 3
data:
  pipeline:
    sequencer: 17s
    event_filter: nofilt
    break_filter: cumul60br
    adjuster: tscrp
    encoders_aggregators_pairs:
      1:
        - 1hot
        - aveagg
      2:
        - actionspan
        - normagg
      # 5:
      #   - sgenc
      #   - aveagg
      # 6:
      #   - sgenc
      #   - cumulaveagg
      # 7:
      #   - sgenc
      #   - flatagg
    encoders:
      - 1hot
      - sgenc
      - actionspan
    encoder: actionspan
    skipgram_weights: ../data/reproduction/embeddings/
    skipgram_map: ../data/reproduction/repro_skipgrammap.pkl
    aggregator: normagg
  adjuster:
    limit: 999999999
    limits: 
      - 10
      - 20
      - 30
      - 40
      - 50
      - 60
      - 70
      - 80
      - 90
      - 100
      - 150
      - 200
      - 250
      - 300
ML:
  pipeline:
    splitter: stratkf
    sampler: nosplr
    task: classification
    model: blank
    scorer: blank
    gridsearch: supgs
    # xvalidator: early_nested_xval
    models:
      - rf 
      # - 1nn
      # - sknn
    test_pad: False
    val_pad: False
    train_pad: True
  models:
    classifiers:
      rf:
        dummy_parameters:
          - blank
      1nn:
        dummy_parameters:
          - blank
      sknn:
        dummy_parameters:
          - blank
  splitters:
    n_folds: 3
    stratkf:
      shuffle: True
      stratifier_col: y
  xvalidators:
    nested_xval:
      inner_n_folds: 3
      outer_n_folds: 3
      optim_scoring: roc
  scorers:
    scoring_metrics:
      - accuracy
      - balanced_accuracy
      - precision
      - recall
      - roc
      - balanced_auc
      - overall_auc
    carry_on: True
...