---
paths:
  parsed_simulations: '../data/parsed simulations/'
  sequenced_simulations: '../data/sequenced_simulations/'
experiment:
  class_name: contri
  n_classes: 52
  root_name: cluster
  random_seed: 42
  n_folds: 10
data:
  min_length: 10
  pipeline:
    sequencer: minimise
    concatenator:
      type: chemconcat
      tasks: 
        # - '1'
        - '2'
    event_filter: nofilt
    break_filter: cumul60br
    adjuster: full
    encoder: 1hot
    aggregator: noagg
  adjuster:
    limit: 99999999999999
ML:
  pipeline:
    splitter: stratkf
    sampler: nosplr
    task: modelling
    model: pwsg
    scorer: multiclfscorer
    gridsearch: unsupgs
    xvalidator: unsup_nested_xval
  models:
    modellers:
      skipgram:
        padding_value: -10
        window_size: -1
        embeddings: -1
        n_states: 52
        optimiser: adam
        early_stopping: False
        batch_size: 256
        shuffle: True
        epochs: -1
        verbose: 100
  splitters:
    n_folds: 10
    stratkf:
      n_folds: 10
      shuffle: True
      stratifier_col: y
  xvalidators:
    unsup_nested_xval:
      inner_n_folds: 10
      optim_scoring: cce
      flatten_value: -99
      param_grid:
        n_states:
          - 100
        embeddings:
          # - 5
          # - 10
          # - 15
          - 10
          - 15
          - 20
          - 25
        window_size:
          - 4
          - 6
          - 8
        optimiser:
          - adam
        early_stopping:
          - False
        batch_size:
          - 256
        shuffle:
          - True
        epochs:
          # - 1 
          # - 5
          # - 100
          - 200
        verbose:
          - 
  scorers:
    scoring_metrics:
      - cce
...