ML:
  models:
    classifiers:
      1nn:
          metric_reporting:
            - accuracy
            - sparse_categorical_crossentropy
          dense_units: 16
          n_classes: 2
          dropout: 0.2
          early_stopping: True
          verbose: 0
          batch_size: 1
          shuffle: True
          epochs: 5
