dense_units:
  - 8
  - 16
  - 32
  - 64
dropout:
  - 0
  - 0.2
  - 0.4
batch_size:
  - 8
  - 16
shuffle:
  - True
epochs:
  - 200
early_stopping:
  - False
  - True
verbose:
  - 0
metric_reporting:
  - accuracy