batch_size:
- 64
- 32
- 16
cell_type:
- LSTM
- GRU
- BiLSTM
- RNN
dropout:
- 0.2
- 0
- 0.02
- 0.1
early_stopping:
- false
epochs:
- 10
- 30
- 40
- 50
- 60
- 100
loss:
- auc
n_cells:
- - 8
  - 16
  - 8
- - 16
  - 32
  - 16
- - 32
  - 64
  - 32
- - 64
  - 128
  - 64
- - 128
  - 256
  - 128
n_layers:
- 1
- 2
- 3
optimiser:
- adam
padding_value:
- -1
shuffle:
- true
verbose:
- 1
