attention:
  dropout:
  - 0.05
batch_size:
- 64
cnn_cells:
- 32
cnn_window:
- 4
dropout:
- 0.2
early_stopping:
- false
epochs:
- 50
loss:
- auc
lstm_cells:
- 8
optimiser:
- adam
padding:
- valid
padding_value:
- -1
pool_size:
- 50
seed:
- 193
shuffle:
- true
stride:
- 25
verbose:
- 1
flatten:
# - flat
- average
