batch_size:
- 16
cell_type:
- LSTM
- GRU
- BiLSTM
dropout:
- 0
early_stopping:
- true
epochs:
- 150
loss:
- auc
n_cells:
- - 16
- - 32
n_layers:
- 1
optimiser:
- adam
padding_value:
- -1
shuffle:
- true
verbose:
- 1
attention:
  dropout: 
    - 0.05
