batch_size:
- 64
cell_type:
- BiLSTM
dropout:
- 0.2
early_stopping:
- false
epochs:
- 50
loss:
- auc
n_cells:
- - 16
  - 32
n_layers:
- 2
optimiser:
- adam
padding_value:
- -1
shuffle:
- true
verbose:
- 1
