padding_value: 
  - -1
cell_type:
  - LSTM
  - BiLSTM
n_layers:
  # - 1
  - 2
n_cells:
  - 32
  - 64
  # - 128 # If time allows it
dropout:
  # - 0
  - 0.2
  # - 0.5
optimiser:
  - adam
loss:
  - cce
early_stopping:
  - False
batch_size:
  - 64
shuffle:
  - True
epochs:
  - 200
verbose:
  - 1