n_estimators:
  # - 5
  - 3
  - 7
  - 9
  - 11
  - 13
  - 15
  - 17
criterion: 
  - gini
  - entropy
max_depth: 
  - 5
  - 7
  - 9
  - 11
  - 13
min_samples_split: 
  # - 2
  - 3
  - 5
  - 7
  - 9
  - 11
max_leaf_nodes: 
  - ~
max_features: 
  - auto
random_state:
  - 0
class_weight:
  - balanced_subsample