attention:
  dropout:
  - 0.05
batch_size:
- 64
dropout:
- 0.2
early_stopping:
- false
epochs:
- 50
key_cells:
- 5
value_cells:
- 5
query_cells:
- 5
loss:
- auc
optimiser:
- adam
padding:
- valid
padding_value:
- -1
pool_size:
- 50
seed:
- 193
shuffle:
- true
stride:
- 25
verbose:
- 1
gru_cells:
  - 16
  
