attention:
  dropout:
  - 0.05
batch_size:
- 64
dropout:
- 0.02
early_stopping:
- false
epochs:
- 50
key_cells:
- 8
value_cells:
- 8
query_cells:
- 8
loss:
- auc
optimiser:
- adam
padding:
- valid
padding_value:
- -1
pool_size:
- 64
seed:
- 193
shuffle:
- true
stride:
- 32
- 64
verbose:
- 1
gru_cells:
  - 16
  - 32
  
