attention:
  dropout:
  - 0.05
batch_size:
- 64
dropout:
- 0.2
early_stopping:
- false
epochs:
- 50
kvqcells:
- 10
loss:
- auc
optimiser:
- adam
padding:
- valid
padding_value:
- -1
pool_size:
- 100
seed:
- 193
shuffle:
- true
stride:
- 50
verbose:
- 1
